# Generated by Django 3.2.16 on 2022-11-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_auto_20221116_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default slug', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='women',
            name='slug',
            field=models.SlugField(default='default slug', max_length=255, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
